language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: nosetests

# travis notification to irc
notifications:
  irc:
    channels:
      - "irc.freenode.net#ublab"
      - "irc.freenode.net#wikidata"
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"