language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: nosetests -v

# travis notification to irc
notifications:
  irc:
    channels:
      - "irc.freenode.net#ublab"
      - "irc.freenode.net#wikidata"
    on_success: always # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
    template:
      - "%{repository} (%{commit}) : %{author} - %{message} "
      - "Build details: %{build_url}"
    use_notice: true